name: "Generate missing routes"
on:
  schedule:
    # Offset to reduce unnecessary load on GitHub Actions
    - cron: "26 0 */2 * *"
  push:

jobs:
  generate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run start
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git diff-index --quiet HEAD || git commit -m "Update state"
      - run: git push
